# ============================================================
# 源码配置
# ============================================================
source:
  backend:
    - name: "RuoYi-Vue-Plus"
      path: 'D:/java/project/RuoYi-Vue-Plus'
      enabled: true
      git:
        repo: ""
        branch: "main"

  frontend:
    - name: ""
      path: ""
      enabled: true
      git:
        repo: ""
        branch: ""

# ============================================================
# 环境配置
# ============================================================
current_environment: "dev"
environments:
  dev:
    frontend:
      - name: ""
        url: ""

    backend:
      - name: "ruoyi-admin"
        url: "http://localhost:8080"
        description: "主应用服务"
        accounts:
          - role: "admin"
            description: "超级管理员，拥有所有权限"
            username: "admin"
            password: "admin123"
            clientId: "e5cd7e4891bf95d1d19206ce24a7b32e"
            grantType: "password"
            tenantId: "000000"
          - role: "visitor"
            description: "普通用户"
            username: "test"
            password: "666666"
            clientId: "e5cd7e4891bf95d1d19206ce24a7b32e"
            grantType: "password"
            tenantId: "000000"
      - name: "ruoyi-snailjob-server"
        url: "http://localhost:9090"
        description: "Admin 监控服务"
        accounts:
          - role: "admin"
            description: "管理员"
            username: "ruoyi"
            password: "123456"
      - name: "ruoyi-monitor-admin"
        url: "http://localhost:8800"
        description: "任务调度中心服务"
        accounts:
          - role: "admin"
            description: "管理员"
            username: "admin"
            password: "admin"

  test:
    frontend:
      - name: "mall-admin-web"
        url: ""
    backend:
      - name: "mall-tiny"
        url: ""

  staging:
    frontend:
      - name: "mall-admin-web"
        url: ""
    backend:
      - name: "mall-tiny"
        url: ""

# ============================================================
# 测试工具配置
# ============================================================
tools:
  python: "D:/python/Python314/bin"
  jmeter: "D:/java/apache-jmeter-5.6.3/bin"
  git: "D:/tools/git/Git"